### ISSUE TITLE
alot without config file crashes at startup

### ISSUE THREAD

**Issue by vivien** [pazz/alot#1094]
Hi, I am writing a Dockerfile to build and run alot in an isolated container.

I followed the instructions in the manual to write this Debian-based Dockerfile: http://ix.io/yHW
(note that python-pip is missing in the package list.)

Installing this Dockerfile, building and running the container with:
````
$ cd alot/
$ curl -Ss http://ix.io/yHW > Dockerfile
$ docker build -t alot .
$ docker run -ti --rm -e HOME=$HOME -e USER=$USER -v $HOME:$HOME alot
````
immediately crashes with:
````
Traceback (most recent call last):
  File "/usr/local/bin/alot", line 9, in <module>
    load_entry_point('alot==0.6.0dev', 'console_scripts', 'alot')()
  File "/usr/local/lib/python2.7/dist-packages/alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/usr/local/lib/python2.7/dist-packages/alot/ui.py", line 77, in __init__
    global_att = settings.get_theming_attribute('global', 'body')
  File "/usr/local/lib/python2.7/dist-packages/alot/settings/manager.py", line 266, in get_theming_attribute
    return self._theme.get_attribute(colours, mode, name, part)
AttributeError: 'NoneType' object has no attribute 'get_attribute'
````

I am missing something?

P.S.: if there is an interest for Docker support, I'll send a PR. I'm sure people hating Python and its dependency hell will appreciate it :-)

**Comment by dcbaker** [comment]
aside: I would rather not have the docker in tree since I doubt it will be properly maintained, nor do I understand why you'd install alot (which has very few dependencies) if you don't want python on your system, there are plenty of other notmuch frontends (emacs, neomutt, asteroid, etc) if python is a problem, nor do I think docker is a good solution for installing desktop apps.

As for the actual problem: for some reason the default theme isn't being loaded, which I don't really understand how that's happening, the SettingsManager should be doing that in it's constructor.

Can you run alot with `-d debug -l <some log file name>` and post the contents?

**Comment by vivien** [comment]
> aside: I would rather not have the docker in tree since I doubt it will be properly maintained, nor do I understand why you'd install alot (which has very few dependencies)

Well this is very subjective. alot comes with quite a few packages, so the installation may not be trivial at lot. Maybe that's usual for pythonists, but it can be reluctant to others. But it won't be fair to judge the software only from this anyway.

> Can you run alot with `-d debug -l <some log file name>` and post the contents?

````
+ exec su vivien -c 'cd /home/vivien; alot -d debug -l /tmp/alot'
Traceback (most recent call last):
  File "/usr/local/bin/alot", line 9, in <module>
    load_entry_point('alot==0.6.0dev', 'console_scripts', 'alot')()
  File "/usr/local/lib/python2.7/dist-packages/alot-0.6.0dev-py2.7.egg/alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/usr/local/lib/python2.7/dist-packages/alot-0.6.0dev-py2.7.egg/alot/ui.py", line 77, in __init__
    global_att = settings.get_theming_attribute('global', 'body')
  File "/usr/local/lib/python2.7/dist-packages/alot-0.6.0dev-py2.7.egg/alot/settings/manager.py", line 266, in get_theming_attribute
    return self._theme.get_attribute(colours, mode, name, part)
AttributeError: 'NoneType' object has no attribute 'get_attribute'
/ # cat /tmp/alot 
/ #
````

BTW, do you know how I can run alot from the source directly? I guess `python setup.py install` is only meant to deploy the program into the PATH.

Thanks!

**Comment by dcbaker** [comment]
To run locally `PYTHONPATH=. python2 alot/__main__.py` is how I run it when I want to run locally.

Is the container "containing" /tmp/alot"? because there should be something in the log file even without setting the debug level.

**Comment by vivien** [comment]
Docker doesn't matter here. I've installed the AUR packages for `python2-urwidtrees` and `alot-git` and I also get an empty log file:
````
$ alot -d debug -l /tmp/alot.dbg ; cat /tmp/alot.dbg
Traceback (most recent call last):
  File "/usr/bin/alot", line 11, in <module>
    load_entry_point('alot==0.6.0.dev0', 'console_scripts', 'alot')()
  File "/usr/lib/python2.7/site-packages/alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 77, in __init__
    global_att = settings.get_theming_attribute('global', 'body')
  File "/usr/lib/python2.7/site-packages/alot/settings/manager.py", line 266, in get_theming_attribute
    return self._theme.get_attribute(colours, mode, name, part)
AttributeError: 'NoneType' object has no attribute 'get_attribute'
````
And the same happens from the source:
````
$ PYTHONPATH=. python2 alot/__main__.py
Traceback (most recent call last):
  File "alot/__main__.py", line 139, in <module>
    main()
  File "alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/home/vivien/Projects/alot/alot/ui.py", line 77, in __init__
    global_att = settings.get_theming_attribute('global', 'body')
  File "/home/vivien/Projects/alot/alot/settings/manager.py", line 266, in get_theming_attribute
    return self._theme.get_attribute(colours, mode, name, part)
AttributeError: 'NoneType' object has no attribute 'get_attribute'
````

**Comment by dcbaker** [comment]
That's very interesting, since I maintain the alot-git aur package and don't see the same error. hmmmmmmm..... I guess I'll write some tests for that code sooner than later :)

Out of curiosity, do you have the environment variable XDG_DATA_DIRS set?

**Comment by vivien** [comment]
I do have XDG_DATA_DIRS set.

**Comment by dcbaker** [comment]
What's it set to?

**Comment by dcbaker** [comment]
I think I know what happened.

**Comment by vivien** [comment]
````
$ echo $XDG_DATA_DIRS
/home/vivien/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
````

**Comment by vivien** [comment]
here we go. Bisecting against 0.5.1 which is good:
````
86186a242c11fcbc501e7afc791a50187e0dd574 is the first bad commit
commit 86186a242c11fcbc501e7afc791a50187e0dd574
Author: Dylan Baker <dylan@pnwbakers.com>
Date:   Fri Jun 16 15:44:59 2017 -0700

    settings: Add a reload method
    
    This patch does a bit of refactoring to the Settings class for it's
    setup, and adds a reload method. The refactoring encapsulates the
    handling of NoneType for the read_*config methods, and reworks the
    constructor just a bit so that it doesn't rely on calling methods to
    create instance variables.
    
    The end result is slightly cleaner, and will be useful for adding a
    reload command to alot itself.

:040000 040000 82293ae3e74ca4230937f59dbc66601ba5180764 ca9848a3d37c9a122ad68ddc0f83993f720bf6ac M	alot
:040000 040000 c2d046ccba68064c33f6b82c4fb950f26adcd2c1 652696dc7060ae9f765337971e2b36ef79daac10 M	tests
````

**Comment by dcbaker** [comment]
that seems like a sane setting.

Do you have an ~/.config/alot/config file? Because you could definately end up with problems in that case.

**Comment by vivien** [comment]
no I don't... `touch ~/.config/alot/config` indeed fixes the issue...

**Comment by dcbaker** [comment]
sigh. Trying to reduce indentation for the lose. I'll send a patch in a minute.

**Comment by vivien** [comment]
I applied https://github.com/dcbaker/alot/commit/5706feac8bd6445367bb2507ddc7130b3830f828.patch locally and this indeeds fixes alot startup without config file.

**Comment by dcbaker** [comment]
I would like to leave this open while the bug is still present in master, to help us keep track of closing it with a patch.
