### ISSUE TITLE
Hooks broken by updates

### ISSUE THREAD

**Issue by foobacca** [pazz/alot#692]
With the latest alot, my hooks broke as they are being passed an extra argument (cmd).  We could at least do with making it easier to work out what the issue is.  The error I got was:

```
pre_envelope_send() got an unexpected keyword argument 'cmd'
```

Using the debug log, I got this stack trace:

```
DEBUG:ui:Got key (['y'], [121])
DEBUG:ui:cmdline: 'send'
DEBUG:ui:envelope command string: "send"
DEBUG:__init__:mode:envelope got commandline "send"
DEBUG:__init__:ARGS: [u'send']
DEBUG:__init__:cmd parms {}
ERROR:ui:Traceback (most recent call last):
  File "/home/hamish/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 286, in addCallbacks
    self._runCallbacks()
  File "/home/hamish/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 542, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/hamish/dev/alot/alot/ui.py", line 200, in apply_this_command
    return self.apply_command(cmd)
  File "/home/hamish/dev/alot/alot/ui.py", line 641, in apply_command
    d = defer.maybeDeferred(prehook, ui=self, dbm=self.dbman, cmd=cmd)
--- <exception caught here> ---
  File "/home/hamish/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 133, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hamish/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1141, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
exceptions.TypeError: pre_envelope_send() got an unexpected keyword argument 'cmd'
```

This does not include a reference to the hook file which has the code which needs to be updated.

It would be nice to at least show a more useful error message.  We should also put something in the release notes about having to update the hooks.

Maybe we could put a try/except block around alot/ui.py line 641, and if we get a TypeError which mentions "unexpected keyword argument" we could print an error that says you need to update your hooks (though the error text might be translated of course).  We could even check the hook arguments somewhere in the code to catch this early.  Might try coding an example of how to deal with this.

The change that causes this was introduced in commit fc0a508350074eae0ea47a520659d43a05451111 (Tue 06 Aug 2013 19:56:26 BST)
