### ISSUE TITLE
initial_command did work on 0.8

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#1373]
Hello ! :coffee: 

**Describe the bug**
I use 2 query on started to populate 2 buffer, and now it start blank, the queries works and I can open them manually, I used `initial_command` maybe I miss some config information ?

**Software Versions**
- Python version:
python-3.6
- Notmuch version: [if relevant]
notmuch-0.27
- Alot version:
alot-0.8

**To Reproduce**
1. Add a initial_command query in the config file
2. run alot

**Error Log**
I don't see anything relative in the log

Guillaume.

**Comment by pazz** [comment]
very strange. can we see the relevant parts of  your config?
Out of interest, have you tried python 3.7?

**Comment by GuillaumeSeren** [comment]
Hey @pazz 

> very strange. can we see the relevant parts of your config?
Yes again worked fine with the 0.7, nothing fancy just open 2 buffer with 2 queries,
1 for the important and 1 for the mailing list

```
initial_command = search tag:inbox AND tag:unread AND NOT tag:spam AND NOT tag:lists OR tag:important;search tag:lists and tag:unread and not tag:spam and not tag:important and not tag:new;buffer 0
```

**Comment by pazz** [comment]
Try quoting it?
It is possible that a new (py3) version of configobj has different behaviour..


Quoting Guillaume Seren (2019-02-03 18:36:55)

**Comment by mbauhardt** [comment]
I have the same behaviour.
My initial_command is 
```
initial_command = bufferlist; taglist; call hooks.searchByTag(); buffer 0
```

My hook `searchByTag()` has the following content
```
def searchByTag():
  file = open("/Users/mb/.config/alot/search.txt", "r")
  s = file.read()
  file.close()
  ui.apply_command(s)
```
My buffer contains bufferlist and taglist, but the result from the  search  of my hooks file.

The log file is empty as well. But.....
When I start alot, there is a very short amount of time where I can see an error message which disappears almost directly after program startup.
```
RuntimeWarning: coroutine UI.apply_command was never awaited.
```
So I assume the code within my function `searchByTag` is not correct. Any hints....

thx
marko

**Comment by pazz** [comment]
I believe you need to `await ui.apply_command(s)`, and not simply call it as you do in your hook code.
Moreover, I am not 100% sure about how configobj handles your config but I'd recommend to quote the initial_command, as in

```
initial_command = "bufferlist; taglist; call hooks.searchByTag(); buffer 0"
```

**Comment by mbauhardt** [comment]
if i'm using `await` and the quotation, i get the following error log statements in my log file
```
ERROR:manager:unable to load hooks file:/Users/mb/.config/alot/hooks.py
Traceback (most recent call last):
  File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python3.7/site-packages/alot/settings/manager.py", line 84, in read_config
    spec.loader.exec_module(self.hooks)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mb/.config/alot/hooks.py", line 10
    await ui.apply_command(s)
    ^
SyntaxError: 'await' outside async function
INFO:ui:setup gui in 256 colours
ERROR:globals:module 'hooks' has no attribute 'searchByTag'
Traceback (most recent call last):
  File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python3.7/site-packages/alot/commands/globals.py", line 408, in apply
    t = eval(self.command)
  File "<string>", line 1, in <module>
AttributeError: module 'hooks' has no attribute 'searchByTag'

```

**Comment by pazz** [comment]
Yes, your hook also needs to be a coroutine (defined via `async def`) ...

**Comment by mbauhardt** [comment]
When using `async`...

```
async def searchByTag():
  file = open("/Users/mb/.config/alot/search.txt", "r")
  s = file.read()
  file.close()
  await ui.apply_command(s)
```
Then I get 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python3.7/site-packages/alot/commands/globals.py", line 410, in apply
    await t
  File "/Users/mb/.config/alot/hooks.py", line 10, in searchByTag
    await ui.apply_command(s)
  File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python3.7/site-packages/alot/ui.py", line 705, in apply_command
    if cmd.prehook:
AttributeError: 'str' object has no attribute 'prehook'

```

**Comment by pazz** [comment]
You either need to give `apply_command` a Command object as parameter, or instead use `apply_commandline` (IIRC), with your string.

**Comment by mbauhardt** [comment]
Boom, here we go.
```
async def searchByTag():
  file = open("/Users/mb/.config/alot/search.txt", "r")
  s = file.read()
  file.close()
  await ui.apply_commandline(s)
```
Is working from my side.
I mean it tooks a while until all the search buffers are there but at the end I have my pre-configured search buffers back.

thanks
marko

**Comment by pazz** [comment]
sorry I closed this prematurely. The original issue may still be open. Perhaps it is related to some missing (internal) `refresh`?

**Comment by GuillaumeSeren** [comment]
Hey,
since I bumped twisted to 18.4 version it is now working on my setup.
So I think it comes from that module.

**Comment by pazz** [comment]
thanks for the update. I've pushed your PR regarding bumping twisted.
