### ISSUE TITLE
Can not send because `Header` has no `splitlines()`

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1289]
python3.6.6, notmuch 0.27, alot master (0.7-252-gcc33e18a)

I can not `:send` or `:save` an email from the envelope buffer. The log has this exception. (To reproduce just `:compose` anything and try to `:send` it)
```
ERROR:ui:Traceback (most recent call last):
  File "/home/luc/vcs/alot/alot/ui.py", line 709, in apply_command
    await cmd.apply(self)
  File "/home/luc/vcs/alot/alot/commands/envelope.py", line 214, in apply
    self.mail = self.mail.as_string(policy=email.policy.SMTP)
  File "/usr/lib/python3.6/email/message.py", line 158, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.6/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.6/email/generator.py", line 195, in _write
    self._write_headers(msg)
  File "/usr/lib/python3.6/email/generator.py", line 222, in _write_headers
    self.write(self.policy.fold(h, v))
  File "/usr/lib/python3.6/email/policy.py", line 183, in fold
    return self._fold(name, value, refold_binary=True)
  File "/usr/lib/python3.6/email/policy.py", line 207, in _fold
    lines = value.splitlines()
AttributeError: 'Header' object has no attribute 'splitlines'
```

**Comment by lucc** [comment]
The offending commit seems to be 293bf7ad89c837d6a2ee9e08443c00703172d953 as it did also not work after the merge (29eb19863eccedec0d5a6e41a1ab8f9b7cce66b4) but it did work before the branch (834a658dfbe25707eebed34d5f5fdd10e1fddd60).

**Comment by pazz** [comment]
outch!
What works for me is simply using str instead of `Header` objects. (see below).
I've probably missed some such removals, because this does not fully workd with attachments, encryption or signatures..

```patch
--- a/alot/db/utils.py
+++ b/alot/db/utils.py
@@ -528,9 +528,9 @@ def encode_header(key, value):
             # append address part encoded as ascii
             entry = email.utils.formataddr((namepart.encode(), address))
             encodedentries.append(entry)
-        value = Header(', '.join(encodedentries))
+        value = ', '.join(encodedentries)
     else:
-        value = Header(value)
+        value = value
     return value
 

```

**Comment by dcbaker** [comment]
Ooof, what a thing to not have any tests for. I'm looking into this, it's strange that `mail.as_string()` doesn't error, but `mail.as_string(policy=email.policy.SMTP)` does.
