### ISSUE TITLE
Message instance has no attribute 'iteritems' trying to show headers

### ISSUE THREAD

**Issue by varac** [pazz/alot#1016]
I get this with latest alot:master from today: 

```
tail: /tmp/alot.log: file truncated
INFO:ui:setup gui in 256 colours
INFO:search:open thread view for thread:000000000001c88b: Re: Test
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.5-py2.7.egg/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.5-py2.7.egg/alot/commands/thread.py", line 601, in apply
    mt.reassemble()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.5-py2.7.egg/alot/widgets/thread.py", line 178, in reassemble
    self._maintree._treelist = self._assemble_structure()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.5-py2.7.egg/alot/widgets/thread.py", line 198, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.5-py2.7.egg/alot/widgets/thread.py", line 248, in _get_headers
    self._all_headers_tree = self.construct_header_pile()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.5-py2.7.egg/alot/widgets/thread.py", line 274, in construct_header_pile
    for key, value in mail.iteritems():
exceptions.AttributeError: Message instance has no attribute 'iteritems'
```

I'm using notmuch 0.23.1-1ubuntu4.

**Comment by dcbaker** [comment]
That's a pretty simple fix, just need to change iteritems to items.

I'm on mobile, please excuse autocorrect fail.

**Comment by varac** [comment]
@dcbaker thx for the quick reply. I digged  a bit myself and found an old alot installation in a different path that got preferred and messed things up. After reinstalling that old version, it works with alot 0.5 now.

**Comment by pazz** [comment]
Right, thanks for confirming this. I was just going to reply that I cannot reproduce this.

**Comment by varac** [comment]
Sorry, I commented on the wrong issue - It's actually not fixed and I get it all the time I want to show headers :(

**Comment by pazz** [comment]
OK in this case I need more input. I cannot reproduce this.

**Comment by varac** [comment]
@dcbaker sounds good.
@dcbaker @pazz Pls tell me what you need and how I can provide more input .

**Comment by pazz** [comment]
how do you trigger this bug? Just by firing the `togglesource` command in a thread buffer?

**Comment by varac** [comment]
exactly, by pressing 'H'

**Comment by dcbaker** [comment]
I can reproduce this, and I have a patch.

**Comment by dcbaker** [comment]
More critically this bug is present in the released 0.5

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-01-30 17:25:30)
>    More critically this bug is present in the released 0.5

yes. should we wait or simply silently make a point release?
Strange that it is not a problem for me though.

**Comment by dcbaker** [comment]
@pazz I only noticed it when I tried to add addresses to abook using `pipeto --shell --format decoded -- abook --add-email`.

I think it might be worth pushing out a 0.5.1 tag withis this patch. I suspect that we're going to get more reports of this issue, and since 0.5 just came out... Would you like me to make the tag or do you want to?

**Comment by pazz** [comment]
I can do it. But I'll leave out an extra release mail for this.

**Comment by dcbaker** [comment]
that seems fine.
